use_frameworks!

platform :ios, '12.0'

target 'DynamicMapper_Example' do
  pod 'DynamicMapper', :path => '../'
   pod 'RealmSwift', '~>10'
  target 'DynamicMapper_Tests' do
    inherit! :search_paths

    
  end
end
